// You can add your native dependencies here
dependencies {
//  implementation 'androidx.multidex:multidex:2.0.1'
}

android {
  namespace "org.nativescript.shadowHour"
  compileSdkVersion 35
  buildToolsVersion "35"
  // ndkVersion ""

  defaultConfig {
    applicationId "org.nativescript.shadowHour"
    minSdkVersion 24
    targetSdkVersion 35

    // Version Information
    versionCode 1
    versionName "1.0.0"

    generatedDensities = []
  }

  aaptOptions {
    additionalParameters "--no-version-vectors"
  }

  // 自定义 APK 输出名称
  applicationVariants.all { variant ->
    variant.outputs.all {
      def versionName = variant.versionName
      def buildType = variant.buildType.name
      outputFileName = "shadowHour-${versionName}-${buildType}.apk"
    }
  }
}
